version: "3"

services:
  db:
    container_name: django_db
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: password
    image: postgres:11
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
      - "./backup:/var/lib/postgresql"
    expose:
      - "5432"

  app:
    container_name: django_app
    env_file:
       - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    command: gunicorn project.wsgi:application --name django_app --workers 3 --bind=0.0.0.0:8000 --log-level=debug --log-file=-
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - db
  
  web:
    container_name: django_nginx
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8000:8000"
    depends_on:
      - app
