version: "3"

services:
  db:
    container_name: django_db
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: password
    image: postgres
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
      - "./backup:/var/lib/postgresql/backup"
    expose:
      - "5432"
  
  db2:
    container_name: django_db2
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: password
    image: postgres
    command: -p 5433
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
    expose:
      - "5433"

  app:
    container_name: django_app
    env_file:
       - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - db
      - db2
  
  web:
    container_name: django_nginx
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8000:8000"
    depends_on:
      - app
