version: "3"

services:

  db:
    container_name: django_pg
    image: postgres:alpine
    volumes: 
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "django_db"
    expose: 
      - 5432
    ports:
      - "5432:5432"

  app:
    container_name: django_app
    environment:
      DJANGO_MANAGEPY_MIGRATE: "on"
    build:
      context: .
      dockerfile: ./Dockerfile
    command: pipenv run gunicorn project.wsgi:application --workers 3 -b 0.0.0.0:8000 --log-level=debug --log-file=-
    depends_on:
      - db
    volumes:
      - .:/code
    expose:
      - "8000"

  nginx:
    container_name: django_nginx
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app

volumes:
  pgdata:
